### ISSUE TITLE
fsharpbinding is not available as the default package in SublimeText package control

### ISSUE THREAD

**Issue by vors** [fsharp/fsharpbinding#996]
I prepared a pull request to add it.
https://github.com/vors/package_control_channel/pull/1

@guillermooo what do you think?

**Comment by guillermooo** [comment]
Hm. I'm wondering whether this would work. Wouldn't PC clone the whole fsharpbinding (emacs, etc.) into the ST Data dir? ST would find the syntax definition, but any .py plugin would fail to load.

I think we need to publish to PC from a separate repo. Or am I missing something?

**Comment by rneatherway** [comment]
I think as discussed on #990 we are planning to split the repo so that FSharp.AutoComplete stays here, and the editor-specific components (emacs, vim and sublime) will each go to a new repo. each of these could either be a clone of this repo (with everything else deleted, or using `git filter-branch`), or just a fresh repo if the history isn't important.

I will then setup FSharp.AutoComplete to do binary github releases (like https://github.com/fsprojects/Paket/releases), which the editor components can download as part of their install scripts if desired as an alternative to bundling it or asking people to compile it.

**Comment by rneatherway** [comment]
This is done @guillermooo ?

**Comment by guillermooo** [comment]
It is. Closing.
